<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BillSetting extends Model
{

    protected $table = 'Tb_Bill_Setting';
    protected $fillable = [
        'st_Guid',
        'Bill_Type_FK',
        'Item_Ch_Qty',
        'Pay_Type',
        'FormText',
        'Acc_Guid',
        'Acc_Visible',
        'Acc_Contra_Guid',
        'Acc_Contra_Visible',
        'Cust_Acc_Guid',
        'Cust_Acc_Visible',
        'Store_Guid',
        'Discount_Guid',
        'Discount_Visible',
        'CurrencyGuid',
        'Currency_Visible',
        'RowTS',
        'Item_Ch_Highx',
        'Item_Ch_Lowx',
        'Item_Ch_OrderLimitx',
        'Item_Ch_Zero',
        'Cost_Guid',
        'Cost_Visible',
        'Store_Visible',
        'us_Guid',
        'Save_And_Print',
        'Show_Before_Print',
        'Item_Barcode',
        'Item_Code',
        'Item_Name',
        'Item_Qty1',
        'Item_Qty2',
        'Item_Qty3',
        'Item_Price',
        'Item_Price_Total',
        'Item_Discount',
        'Item_Extra',
        'Item_Price_Net',
        'Unit_Type',
        'Item_Notes_Show',
        'Item_Length',
        'Item_width',
        'Item_Count',
        'Item_Image',
        'ProductionDate',
        'ExpireDateAlert',
        'Branch_Guid',
        'PercentagePrice',
        'Print_Count',
        'Print_Temp',
        'IsCombine',
        'No_Copy_Print',
        'BodyColor_Odd',
        'BodyColor_Even',
        'Qty_MustGreaterThanZero',
        'Qty_MustGreaterThanZeroInStore',
        'ItemPrice_MustNotEqualZero',
        'Save_And_New',
        'CostPriceAffectedByDissAdd',
        'CloseBillAfterPayment',
        'DiscountAmount',
        'DiscountPercent',
        'DiscountPercentAffect',
        'AddAmount',
        'AddAmountPercent',
        'AddPercentAffect',
        'Header_Cash_Visible',
        'Header_Notes_Visible',
        'Footer_BillTotal',
        'Footer_ItemDiscount',
        'Footer_BillDiscount',
        'Footer_BillAdd',
        'Footer_ItemAdd',
        'Footer_TotalAdd',
        'Footer_TotalDiscount',
        'DisAddGrid_Visible',
        'BodyGrid_Visible',

    ];
}
